# Generated by Django 5.1.1 on 2024-11-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='info_y_bodegas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
